# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArtPassID' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for ArtPassID
  pod 'IQKeyboardManagerSwift'
  pod 'LGSideMenuController'
  pod 'RappleProgressHUD', '~> 4.0'
  pod 'Alamofire', '~> 4.5'
  pod 'SKCountryPicker', '~> 1.2.0'
  pod 'SDWebImage', '~> 4.0'
  pod 'SwiftyStoreKit'
end
